[build]
  functions = "netlify/functions"
  command = "npm install"

[functions."*"]
  timeout = 26

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
